const nomeParam = { key: 'nome', label: 'Nome', default: 'Teste' };
const subParam = { key: 'sub', label: 'Subtítulo', default: 'Teste' };
const localParam = { key: 'local', label: 'Local', default: 'Estúdio' };

export const GROUPS = [
  {
    title: 'Telas',
    items: [
      { name: 'Tela Geral', path: '/telas/tela-geral' },
      { name: 'Tela Esporte', path: '/telas/tela-esporte' },
      { name: 'Tela Conexão', path: '/telas/tela-conexao' },
      { name: 'Tela Corpo e Mente', path: '/telas/tela-corpo-mente' },
      { name: 'Tela Mistura Boa', path: '/telas/tela-mistura-boa' },
    ],
  },
  {
    title: 'Programação',
    items: [
      { name: 'Programação (Atual / Próximo)', path: '/programacao' },
      { name: 'Programação Geral', path: '/programacaoGeral' },
      { name: 'Programação Esporte', path: '/programacaoEsporte' },
      { name: 'Programação Conexão', path: '/programacaoConexao' },
      { name: 'Programação Pensar Negócios', path: '/programacaoPensarNegocios' },
      { name: 'Programação Outros', path: '/programacaoOutros' },
      { name: 'Programação Corpo e Mente', path: '/programacaoCorpoEMente' },
      { name: 'Programação Pelotas Merece', path: '/programacaoPelotasMerece' },
      { name: 'Programação A Hora', path: '/programacaoAHora' },
    ],
  },
  {
    title: 'Cenas (Tempo)',
    items: [
      { name: 'Tempo Geral', path: '/' },
      { name: 'Tempo Esporte', path: '/esporte' },
      { name: 'Tempo Conexão', path: '/conexao' },
      { name: 'Tempo Pensar Negócios', path: '/pensarNegocios' },
      { name: 'Tempo Outros', path: '/outros' },
      { name: 'Tempo Corpo e Mente', path: '/corpoEMente' },
      { name: 'Tempo Pelotas Merece', path: '/pelotasMerece' },
      { name: 'Tempo Mistura Boa', path: '/misturaBoa' },
    ],
  },
  {
    title: 'Relógios',
    items: [
      { name: 'Relógio Geral', path: '/clock' },
      { name: 'Relógio Esporte', path: '/clockEsporte' },
      { name: 'Relógio Conexão', path: '/clockConexao' },
      { name: 'Relógio Pensar Negócios', path: '/clockPensarNegocios' },
      { name: 'Relógio Outros', path: '/clockOutros' },
      { name: 'Relógio Corpo e Mente', path: '/clockCorpoEMente' },
      { name: 'Relógio Pelotas Merece', path: '/clockPelotasMerece' },
      { name: 'Relógio A Hora', path: '/clockAHora' },
      { name: 'Relógio Mistura Boa', path: '/clockMisturaBoa' },
    ],
  },
  {
    title: 'Lower',
    items: [
      { name: 'Lower Teste (Portal)', path: '/lowerTeste' },
      { name: 'Lower Geral', path: '/lower' },
      { name: 'Lower Esporte', path: '/lowerEsporte' },
      { name: 'Lower Conexão', path: '/lowerConexao' },
      { name: 'Lower Pensar Negócios', path: '/lowerPensarNegocios' },
      { name: 'Lower Outros', path: '/lowerOutros' },
      { name: 'Lower Corpo e Mente', path: '/lowerCorpoEMente' },
      { name: 'Lower Pelotas Merece', path: '/lowerPelotasMerece' },
      { name: 'Lower A Hora', path: '/LowerAHora' },
      { name: 'Lower Mistura Boa', path: '/lowerMisturaBoa' },
    ],
  },
  {
    title: 'Instagram',
    items: [
      { name: 'Instagram Geral', path: '/insta' },
      { name: 'Instagram Esporte', path: '/instaEsporte' },
      { name: 'Instagram Conexão', path: '/instaConexao' },
      { name: 'Instagram Pensar Negócios', path: '/instaPensarNegocios' },
      { name: 'Instagram Outros', path: '/instaOutros' },
      { name: 'Instagram Corpo e Mente', path: '/instaCorpoEMente' },
      { name: 'Instagram Pelotas Merece', path: '/instaPelotasMerece' },
    ],
  },
  {
    title: 'WhatsApp',
    items: [
      { name: 'WhatsApp Geral', path: '/whats' },
      { name: 'WhatsApp Esporte', path: '/whatsEsporte' },
      { name: 'WhatsApp Conexão', path: '/whatsConexao' },
      { name: 'WhatsApp Pensar Negócios', path: '/whatsPensarNegocios' },
      { name: 'WhatsApp Outros', path: '/whatsOutros' },
      { name: 'WhatsApp Corpo e Mente', path: '/whatsCorpoEMente' },
      { name: 'WhatsApp Pelotas Merece', path: '/whatsPelotasMerece' },
      { name: 'WhatsApp Mistura Boa', path: '/whatsMisturaBoa' },
    ],
  },
  {
    title: 'Pin',
    items: [
      { name: 'Pin Geral', path: '/pin' },
      { name: 'Pin Esporte', path: '/pinEsporte' },
      { name: 'Pin Conexão', path: '/pinConexao' },
      { name: 'Pin Pensar Negócios', path: '/pinPensarNegocios' },
      { name: 'Pin Outros', path: '/pinOutros' },
      { name: 'Pin Corpo e Mente', path: '/pinCorpoEMente' },
      { name: 'Pin Pelotas Merece', path: '/pinPelotasMerece' },
      { name: 'Pin A Hora', path: '/pinAHora' },
      { name: 'Pin Mistura Boa', path: '/pinMisturaBoa' },
    ],
  },
  {
    title: 'Let',
    items: [
      { name: 'Let Geral', path: '/let', params: [nomeParam] },
      { name: 'Let Teste', path: '/letTest', params: [nomeParam, subParam] },
      { name: 'Let Teste Esporte', path: '/letTestEsporte', params: [nomeParam, subParam] },
      { name: 'Let Teste Conexão', path: '/letTestConexao', params: [nomeParam, subParam] },
      { name: 'Let Teste Pensar Negócios', path: '/letTestPensarNegocios', params: [nomeParam, subParam] },
      { name: 'Let Teste Outros', path: '/letTestOutros', params: [nomeParam, subParam] },
      { name: 'Let Teste Corpo e Mente', path: '/letTestCorpoEMente', params: [nomeParam, subParam] },
      { name: 'Let Teste Pelotas Merece', path: '/letTestPelotasMerece', params: [nomeParam, subParam] },
      { name: 'Let Teste A Hora', path: '/letTestAHora', params: [nomeParam, subParam] },
      { name: 'Let Esporte', path: '/letEsporte', params: [nomeParam] },
      { name: 'Let Conexão', path: '/letConexao', params: [nomeParam] },
    ],
  },
  {
    title: 'GC',
    items: [
      { name: 'GC Geral', path: '/gc', params: [nomeParam] },
      { name: 'GC Esporte', path: '/gcEsporte', params: [nomeParam] },
      { name: 'GC Conexão', path: '/gcConexao', params: [nomeParam] },
      { name: 'GC Pensar Negócios', path: '/gcPensarNegocios', params: [nomeParam] },
      { name: 'GC Outros', path: '/gcOutros', params: [nomeParam] },
      { name: 'GC Corpo e Mente', path: '/gcCorpoEMente', params: [nomeParam] },
      { name: 'GC Pelotas Merece', path: '/gcPelotasMerece', params: [nomeParam] },
      { name: 'GC A Hora', path: '/gcAHora', params: [nomeParam] },
      { name: 'GC Mistura Boa', path: '/gcMisturaBoa', params: [nomeParam] },
    ],
  },
  {
    title: 'GC Música',
    items: [
      { name: 'GC Música Geral', path: '/gcMusica', params: [nomeParam] },
      { name: 'GC Música Esporte', path: '/gcMusicaEsporte', params: [nomeParam] },
      { name: 'GC Música Conexão', path: '/gcMusicaConexao', params: [nomeParam] },
      { name: 'GC Música Pensar Negócios', path: '/gcMusicaPensarNegocios', params: [nomeParam] },
      { name: 'GC Música Outros', path: '/gcMusicaOutros', params: [nomeParam] },
      { name: 'GC Música Corpo e Mente', path: '/gcMusicaCorpoEMente', params: [nomeParam] },
      { name: 'GC Música Pelotas Merece', path: '/gcMusicaPelotasMerece', params: [nomeParam] },
    ],
  },
  {
    title: 'Loc Câmera',
    items: [
      { name: 'Loc. Câmera Geral', path: '/camTp', params: [localParam] },
      { name: 'Loc. Câmera Esporte', path: '/camTpEsporte', params: [localParam] },
      { name: 'Loc. Câmera Conexão', path: '/camTpConexao', params: [localParam] },
      { name: 'Loc. Câmera Pensar Negócios', path: '/camTpPensarNegocios', params: [localParam] },
      { name: 'Loc. Câmera Corpo e Mente', path: '/camTpCorpoEMente', params: [localParam] },
      { name: 'Loc. Câmera Pelotas Merece', path: '/CamTpPelotasMerece', params: [localParam] },
    ],
  },
  {
    title: 'Câmeras',
    items: [
      { name: 'Câmera Una', path: '/camUna' },
      { name: 'Câmera Rio Grande', path: '/camRioGrande' },
      { name: 'Câmera Shopping', path: '/camShopping' },
    ],
  },
  {
    title: 'Esportes',
    items: [
      { name: 'Game Results', path: '/gameResult' },
      { name: 'Live Score', path: '/liveScore' },
      { name: 'Live Score Lower', path: '/liveScoreLower' },
    ],
  },
  {
    title: 'Gravação',
    items: [
      { name: 'Gravado', path: '/gravado' },
      { name: 'REC', path: '/rec' },
      { name: 'No Ar', path: '/noAr' },
      { name: 'Ao Vivo', path: '/aovivo' },
      { name: 'Retransmissão', path: '/retransmissao' },
      { name: 'Lower Gravação', path: '/lowerGravado' },
      {
        name: 'Tela Corpo e Mente Gravação',
        path: '/telas/tela-corpo-mente-gravacao',
      },
      { name: 'Relógio Corpo e Mente Gravado', path: '/clockGravadoCorpoEMente' },
      { name: 'Relógio Mistura Boa Gravado', path: '/clockGravadoMisturaBoa' },
    ],
  },
  {
    title: 'UNO',
    items: [{ name: 'Escala Casa', path: '/Uno/EscalaCasa' }],
  },
];